# Change these first
owner: white-windmills # Your GitHub organization or username, where this repository lives
repo: lostark-status # The name of this repository

sites:
  - name: 👶 LostArk中文论坛
    url: https://www.google.com
    icon: https://cdn.jsdelivr.net/gh/white-windmills/lostark-forum@master/img/lostarkFavicon/lostarkFav.png
  - name: 🚵‍♂️ LostArk地图
    url: https://lost-ark.top/map/
    icon: https://cdn.jsdelivr.net/gh/white-windmills/lostark-forum@master/img/lostarkFavicon/lostarkFav.png
  - name: 🎎 LostArk活动看板
    url: https://timer.lost-ark.top/zh/alarms
    icon: https://cdn.jsdelivr.net/gh/white-windmills/lostark-forum@master/img/lostarkFavicon/lostarkFav.png
  - name: ✨ LostArk好感度看板
    url: https://lost-ark.top/affinity/
    icon: https://cdn.jsdelivr.net/gh/white-windmills/lostark-forum@master/img/lostarkFavicon/lostarkFav.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.lost-ark.top
  # baseUrl: /lostark-status
  favicon: https://cdn.jsdelivr.net/gh/white-windmills/lostark-forum@master/img/whiteWindmillsFavicon/favicon.ico
  logoUrl: https://cdn.jsdelivr.net/gh/white-windmills/lostark-forum@master/img/ww-logo.png
  name: 📊 LostArk中文论坛状态页面
  introTitle: "👋 欢迎来到LostArk中文论坛站点侦测页面"
  introMessage: "🏠 您现在所访问的页面是由**Upptime**提供的站点状态侦测网站，用来提供网站uptime和downtime状态，由于[Upttime](https://upptime.js.org/)服务器位于国外，您可能需要打开代理(vpn)来查看本页面，以获得最好的体验。如果本站因为网络原因**不能正常访问**，欢迎访问[GitHub 仓库](https://github.com/white-windmills/lostark-status/)!"
  navbar:
    - title: "🏡 状态首页"
      href: /
    - title: "⏪ 返回论坛"
      href: https://lost-ark.top/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
